name: DeployToAzureWebApp
 
# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Build-and-Test"]
    types:
      - completed

permissions:
  actions: read
  contents: read

env: 
  app-name: "vaillant"
  rg-name: "ODL-Azure-2349697"

jobs:
  deploy:
    # Only run if CI completed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Download the Build Artifact
      uses: actions/download-artifact@v8
      with:
        # Artifact name
        name: publish
        # Destination path
        path: ${{ runner.temp }}/artifact
        # Run-id
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login via Azure CLI
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        package: ${{ runner.temp }}/artifact
    - name: az cli logout
      run: az logout
