name: KeyVault
 
# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["DeployToAzureWebApp"]
    types:
      - completed


permissions:
  id-token: write
  contents: read

jobs:
  keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v3 
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Retrieve secret from Key Vault
      run: |
        My_SECRET=$(az keyvault secret show --vault-name kv-keyvault-lab-itzel --name MySecret --query value -o tsv)

        echo "MY_SECRET=$MY_SECRET" >> $GITHUB_ENV

    - name: Write retrieved value to text file
      run: |
        echo "${MY_SECRET}" > secret.txt
    
    - name: Upload secret.txt as artifact
      uses: actions/upload-artifact@v4
      with:
        name: secret
        path: secret.txt
